### ISSUE TITLE
byte_string in raw_api

### ISSUE THREAD

**Issue by MoEzRi** [Legrandin/pycryptodome#132]
Hi, there is issue when using the SHA3_512, for python 3.5, you should change to byte_string in _raw_api to tobytes.
thanks for your useful package but you should consider that all features work with out depending on some old libraries like pycrypto.

**Comment by Legrandin** [comment]
Hi,

From your suggestion, I take you want to pass strings to SHA3_512. However, SHA3_512 (as most others primitives) really can only work with `bytes`. The user is expected to encode a string before hashing it (and the library cannot do it for you reliably, since it does not now the target encoding).
