### ISSUE TITLE
"from Crypto.Util import _counter" fails

### ISSUE THREAD

**Issue by tj-murphy** [Legrandin/pycryptodome#137]
Working with some old code that was made for original pycrypto. This code uses _counter.newBE() and that's it. Looking at https://github.com/dlitz/pycrypto/blob/master/lib/Crypto/Util/Counter.py you can also see _counter being imported. I am fine with reconfiguring my code to use something besides _counter.newBE, but I need something that replicates the functionality.

Either there is some other way to handle this, or this limitation should be added to the page https://www.pycryptodome.org/en/latest/src/vs_pycrypto.html

**Comment by Legrandin** [comment]
User code should not be relying on functions private to a module (see how the identifier starts with '_'), for which there is never a guarantee of backward compatibility.

If you show the code we can see how that could be converted, but if it is not related to making a counter block (for CTR) I am afraid it will not be possible.

Closing because this is not an issue of the library.
