### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by spectejb** [Legrandin/pycryptodome#170]
Hello!  If someone is using PyCryptodome, what terms would govern?  

Based on how I read the license file, it appears that when I use PyCryptodome, it is public domain software  but if I contribute code back to the project, that particular code would have a BSD 2-clause license.   Is this correct?  Thanks, in advance, for your help!

**Comment by Legrandin** [comment]
Because of historic reasons, PyCrytodome contains public domain code and BSD2-licensed code (there are also some external test vectors - not code - under Apache 2.0 though). Use and distribution should fulfill the conditions of both licenses (which I don't see as a major problem).

The idea is to - over time - replace public domain code with BSD2-license code,  hence the request for upstream contributions to have such license.
