### ISSUE TITLE
Pip Installation Issue - No Library named Crypto

### ISSUE THREAD

**Issue by pbstrein** [Legrandin/pycryptodome#262]
I ran into an issue installing pycryptodome on Windows 10 on Python 3.6 and 3.7. 

I ran 
```
pip3 install pycryptodome
```
and ran into the following error when trying to import the package. 

```
No module named Crypto
```

After some analysis, it turns out that the package in 
```
/path/to/python/Lib/site-packages/Crypto
```
 was lowercased to "crypto". Changing the folder to Crypto fixed the issue. How can we fix the pip installer/distribution so that this issue does not happen for others?

This looks like the same issue as #235

**Comment by Legrandin** [comment]
Have you installed (maybe by accident) the package [`crypto`](https://pypi.org/project/crypto/)?

According to [this other issue](https://github.com/dlitz/pycrypto/issues/156), if you do so and then install `pycryptodome`, pip will not recognize the conflict and just reuse the `crypto` directory (instead of `Crypto`).

**Comment by Legrandin** [comment]
Hi @pbstrein. Is this still an issue for you? And could you confirm if you had by any chance installed `crypto`? Otherwise I will close the ticket.

**Comment by Legrandin** [comment]
Fixed with an entry in the FAQ: https://www.pycryptodome.org/en/latest/src/faq.html#why-do-i-get-the-error-no-module-named-crypto-on-windows
