### ISSUE TITLE
Porting AES CTR routine from PyCrypto: Size of the counter block (26 bytes) must match block size (16)

### ISSUE THREAD

**Issue by AlisterAmo** [Legrandin/pycryptodome#263]
Hi all
given this code that worked OK in {pycrypto, python 2.7, windows 7 32 bits}  
(edited sensitive values but lenght preserved):
```
        cipher_iv = 123123123123123123123123123123123123123123123123123123123123123
        cipher_key = b'abcdabcdabcdabcd'
        cipher_counter = Counter.new(AES.block_size * 8, initial_value=cipher_iv)
        cipher_aes = AES.new(cipher_key, AES.MODE_CTR, counter=cipher_counter)
        ciphered_file_contents = cipher_aes.encrypt(plain_file_contents_as_bytes)
```
When porting to {pycryptodome, python 3.7, windows 7 32 bits}
I got this weird message stating that the size of the counter block is... 26 bytes long? how?
Do I miss something?

**Comment by Legrandin** [comment]
Your code works with the old PyCrypto because it always **silently** truncates `cipher_iv` to 16 bytes when it is longer than that (in your case the total encoded length of `cipher_iv` is 26 bytes, which explains the error message).

Since silent truncations are very dangerous, I regard that as a bug in PyCrypto.

**Comment by AlisterAmo** [comment]
WHOA, what an oversight on my part, I beg you pardon and thank you very much for slapping me with reality :D 
regards,
AA
