### ISSUE TITLE
When I migrated from PyCrypto to PyCryptodome, I encountered a compatibility problem.

### ISSUE THREAD

**Issue by zgli2011** [Legrandin/pycryptodome#276]
The key used previously was 8 bits long, but when encrypting the complement, it was converted to 24 bits long.
When I changed to pycryptodome, the code prompted: ValueError: Triple DES key degenerates to single DES.
When I browsed the source file Crypto/Cipher/DES3.py, I found this code:
`if key_out[:8]=== key_out [8:16] or key_out[-16:-8]=== key_out[-8:]:
    raise ValueError ("Triple DES key degenerates to single DES")`
There is a contradiction between the check on this side and the `key_size = (16, 24)` below.

Explain:
Why do I need to switch from 8-bit length to 24-bit length?
Because this side is used as HTTP interface verification, other people's HTTP interface is needed, I have no choice.

So I think there should be compatibility here.

**Comment by Legrandin** [comment]
> but when encrypting the complement, it was converted to 24 bits long.

What do you mean exactly? And I guess you mean 8 byte and not 8 bits, and 24 bytes and not 24 bits.

> So I think there should be compatibility here.

The difference in behavior is intentional.

If you have a 168-bit TDES key (3 bytes), there is an expectation that the strenght is equivalent to 168 bits. However, TDES is built in such a way that for some 168-bit keys the effective length is only 56 bits (8 bytes). Some people see it as a feature, but I see it as a security weakness.

PyCryptodome checks for those keys and refuses to use keys that seems secure but actually are not.

**Comment by zgli2011** [comment]
Thank you for your reply. Maybe your idea is better.I have fixed my probleam by change the code.
