### ISSUE TITLE
PBKDF2 is unusable with hmac_hash_module=BLAKE2b

### ISSUE THREAD

**Issue by ulidtko** [Legrandin/pycryptodome#298]
Hi!

Let's say I want to use PBKDF2, exactly for key derivation -- but with some other hash function besides SHA1 or SHA256; let's pick BLAKE2b. Crypto.SE has [no problem with that][•], and the docs seem to suggest that's easily possible, via the `hmac_hash_module` parameter.

However this doesn't work:
```py3
from Cryptodome.Hash import BLAKE2b
from Cryptodome.Protocol.KDF import PBKDF2

PBKDF2(password=b"example", salt=b"salt", dkLen=64, count=2**15,
     hmac_hash_module=BLAKE2b)
```

> AttributeError: module 'Cryptodome.Hash.BLAKE2b' has no attribute 'digest_size'

Welp. Can I monkey-patch this little pity perhaps?..
```py3
>>> BLAKE2b.digest_size = 64
>>> PBKDF2(password=b"example", salt=b"salt", dkLen=64, count=2**15, hmac_hash_module=BLAKE2b)
Traceback (most recent call last):
  File "/home/ulidtko/.local/lib/python3.6/site-packages/Cryptodome/Hash/HMAC.py", line 71, in __init__
    if len(key) <= digestmod.block_size:
AttributeError: module 'Cryptodome.Hash.BLAKE2b' has no attribute 'block_size'

During handling of the above exception, another exception occurred:
    [...]
    raise ValueError("Hash type incompatible to HMAC")
ValueError: Hash type incompatible to HMAC
```
Okay, `BLAKE2b.BLAKE2b_Hash` *class* does have `block_size` attribute, but the *module* does not. Let's push the monkey-patching a bit further:
```py3
>>> BLAKE2b.block_size = 64
>>> PBKDF2(password=b"example", salt=b"salt", dkLen=64, count=2**15, hmac_hash_module=BLAKE2b)
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/ulidtko/.local/lib/python3.6/site-packages/Cryptodome/Protocol/KDF.py", line 151, in PBKDF2
    s = [ prf(password, salt + struct.pack(">I", i)) ] * 2
  File "/home/ulidtko/.local/lib/python3.6/site-packages/Cryptodome/Protocol/KDF.py", line 142, in <lambda>
    prf = lambda p,s: HMAC.new(p, s, hmac_hash_module).digest()
  File "/home/ulidtko/.local/lib/python3.6/site-packages/Cryptodome/Hash/HMAC.py", line 213, in new
    return HMAC(key, msg, digestmod)
  File "/home/ulidtko/.local/lib/python3.6/site-packages/Cryptodome/Hash/HMAC.py", line 86, in __init__
    self._inner = digestmod.new(key_0_ipad)
TypeError: new() takes 0 positional arguments but 1 was given
```
Darn. So now, we have that `BLAKE2b_Hash.new()` accepts the initial `data` through named kwargs-only, but `Hash.HMAC` passes that through a positional argument. It gets uncomfortable, but I can patch that in as well. It **still** doesn't work:
```py3
  [...]
  File "/home/ulidtko/.local/lib/python3.6/site-packages/Cryptodome/Hash/HMAC.py", line 143, in digest
    frozen_outer_hash = self._outer.copy()
AttributeError: 'BLAKE2b_Hash' object has no attribute 'copy'
```

Disappointing. Seems like the `hmac_hash_module` parameter doesn't really work with anything else but SHA1 and SHA256. At the very least, the docs should've been clear about this.

P.S: there's also this suspicion that I'm supposed to wrap the BLAKE2b hash function *in a Cryptodome.Hash.HMAC* instance; however, that gives `TypeError: new() takes 0 positional arguments but 1 was given` just as above; and even if it didn't, `hmac_hash_module` doesn't accept *instances*, only modules.

Does this count as an API bug?.. How can I achieve this rather trivial function composition?

[•]: https://crypto.stackexchange.com/a/52657/11033

**Comment by Legrandin** [comment]
> Let's say I want to use PBKDF2, exactly for key derivation -- but with some other hash function besides SHA1 or SHA256; let's pick BLAKE2b. 

This is not accurate: PBKDF2 needs a PRF, not a hash function. A PRF is a kind of keyed hash, which SHA1 and SHA256 are not, as they have only one input. You can securely turn them into a PRF by using HMAC, which was explicitly designed to mitigate some risks related to the construction underlying SHA1 and SHA-2 (and other Merkle–Damgård hashes).

In other words, PBKDF2 is commonly used with HMAC-SHA1 and HMAC-SHA256 as PRFs: it cannot be used with SHA1 or SHA256 alone.

If you want to use BLAKE2, there is no reason to use HMAC at all (and therefore the `hmac_hash_module` parameter), because BLAKE2 is not a Merkle–Damgård construction. Even more, BLAKE2 was designed to natively operate as a PRF, unlike SHA1 and SHA256 (but like SHA3). You should therefore only use the `prf` parameter.

In practice, one appropriate way to handle it is like this:

    def prf(secret, salt):
        return BLAKE2b.new(key=secret, data=salt).digest()

    key = PBKDF2(b'password', b'salt', prf=prf)

With the caveat that the secret cannot be longer than 64 bytes (as a matter of fact, I think you should pre-hash the password with BLAKE2, but I am not aware of any real standard for combining PBKDF2 and BLAKE2, which is one reason for not using that combination).

With respect to the comment about `digest_size` missing from the BLAKE2 module: it is intentional. BLAKE2 has variable digest size, from 1 to 64 bytes so it impossible to fix a single value.

**Comment by ulidtko** [comment]
Thanks a lot for the explanation, I'm closing the PR.

**Comment by ulidtko** [comment]
Is it also intentional that `blake2b_copy` native function isn't exposed in `BLAKE2b_Hash` as a method?

**Comment by Legrandin** [comment]
Yes, that is also intentional.
