### ISSUE TITLE
Bug with AES-CTR nonce sizes

### ISSUE THREAD

**Issue by Legorooj** [Legrandin/pycryptodome#353]
Unlike what your documentation says, your code doesn't accept the example nonce `b'legoroojlegorooj'`. When I run the below code, I get the error that is shown below that;
```python
NONCE = b'legoroojlegorooj'
aes = AES.new(KEY, AES.MODE_CTR, nonce=NONCE)
```
```
ValueError: Nonce is too long
```
This is a bit of a nuisance for me, because I'm speedtesting this lib against some other crypto library's.

**Comment by Legrandin** [comment]
That is the expected behavior, because `nonce` is the immutable part of the block counter, as described [here](https://www.pycryptodome.org/en/latest/src/cipher/classic.html#ctr-mode). If it's 16 bytes there is no space for the counter.

Most probably, what you really want is to have no nonce at all, just an initial value for the counter. See [here](https://www.pycryptodome.org/en/latest/src/faq.html#is-ctr-cipher-mode-compatible-with-java) for doing that.

**Comment by Legorooj** [comment]
Is it? The [cryptography](cryptography.io) docs say otherwise, and accepts the nonce `b'legoroojlegorooj'`, also giving me an error if I put anything else in (Anything not sixteen bytes long I mean). The [cryptography](cryptography.io) code I'm using ([here](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.modes.CTR)):
```python
cipher = Cipher(algorithms.AES(KEY), modes.CTR(NONCE), default_backend())
```
I need to replicate this code in PyCryptoDome. Can you show me how?

**Comment by Legorooj** [comment]
Their docs also say:
>nonce (bytes-like) – Should be unique, a [nonce](https://cryptography.io/en/latest/glossary/#term-nonce). It is critical to never reuse a `nonce` with a given key. Any reuse of a nonce with the same key compromises the security of every message encrypted with that key. Must be the same number of bytes as the `block_size` of the cipher with a given key. The nonce does not need to be kept secret and may be included with the ciphertext.

**Comment by Legorooj** [comment]
That indicates that the nonce should be 128bits/16bytes AKA `b'legoroojlegorooj'` should work.

**Comment by Legorooj** [comment]
https://chat.stackexchange.com/transcript/message/53027941#53027941 @Legrandin

**Comment by Legrandin** [comment]
The code you are looking for is:

    ivSpec = b'legoroojlegorooj'
    ctr = AES.new(keySpec, AES.MODE_CTR, initial_value=ivSpec)

The `cryptography` library does **not** follow the definition of `nonce` for the CTR mode found in the NIST SP 800-38A standard, annex B2 (i.e. `nonce` = the fixed bytes in the initial counter block, which are never incremented as part of the counter) but rather inherits the meaning of `nonce` from the OpenSSL API (understandable, since `cryptography` is just a wrapper to OpenSSL).

In PyCryptodome, there is a distinction made between the `nonce` and `initial_value` parameters, aligned with the NIST SP 800-38A.

**Comment by Legorooj** [comment]
@Legrandin Ah I see what you mean. Thanks for the clarification - I'll tag you when I release the benchmarking code so you can see cryptodome's performance.

**Comment by Legorooj** [comment]
@Legrandin sorry to come back to this but got to the part of my program that needs this and it's throwing an error. 

```python
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from Crypto.Cipher import AES

KEY = b'legoroojlegorooj'
NONCE_IV = b'legoroojlegorooj'

aes = Cipher(algorithms.AES(KEY), modes.CTR(NONCE_IV), default_backend()).encryptor()
output_data = aes.update(b'Feathers fall as fast as bowling balls.') + aes.finalize()
del aes


ctr = AES.new(KEY, AES.MODE_CTR, initial_value=NONCE_IV)
output_data2 = ctr.encrypt(b'Feathers fall as fast as bowling balls.')

assert output_data == output_data2
```
I need it to A) Not raise Exceptions, B) Have the assert statement work not throw any assertion errors.

**Comment by Legorooj** [comment]
Umm just found another problem:
```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from Crypto.Cipher import AES

KEY = b'legoroojlegorooj'
NONCE_IV = b'legoroojlegorooj'

aes = Cipher(algorithms.AES(KEY), modes.CFB(NONCE_IV), default_backend()).encryptor()
output_data = aes.update(b'Feathers fall as fast as bowling balls.') + aes.finalize()
del aes


ctr = AES.new(KEY, AES.MODE_CFB, iv=NONCE_IV)
output_data2 = ctr.encrypt(b'Feathers fall as fast as bowling balls.')

assert output_data == output_data2
```
@Legrandin apologies for all of these issues...

**Comment by Legrandin** [comment]
For the issue before the last, it's actually my fault as I provided the incomplete example. You should explicitly say that the nonce is empty, like this:

    ctr = AES.new(KEY, AES.MODE_CTR, initial_value=NONCE_IV, nonce=b'')

For the last issue, it is actually due to `cryptography` defaulting to a CFB segment size of 128 bits, and PyCryptodome using 8 bits, so you should have this line instead:

    aes = Cipher(algorithms.AES(KEY), modes.CFB8(NONCE_IV), default_backend()).encryptor()

Or alternatively:

    ctr = AES.new(KEY, AES.MODE_CFB, iv=NONCE_IV, segment_size=128)

**Comment by Legorooj** [comment]
@Legrandin thanks for the help.

**Comment by Legorooj** [comment]
@Legrandin sorry to bother you again but your docs are unclear in this - how can I use `Poly1305` in a way that is compatible with `cryptography`?

**Comment by plusiv** [comment]
Hi! Additionally,

A custom counter can be set, see [this](https://stackoverflow.com/a/45642256/9510988).
