### ISSUE TITLE
RSA CRT Coeffecient is calculated as pInv mod q rather than qInv mod p

### ISSUE THREAD

**Issue by acabey** [Legrandin/pycryptodome#361]
My understanding of the mathematics behind RSA is too limited to understand if this is a real issue or not, but I happened to run into this problem while using this library to convert a non-standard RSA key storage implementation to standard PKCS / PEM.

It seems that most RSA implementations (see openssl [rsa_sp800_56b_gen.c:236](https://github.com/openssl/openssl/blob/651101e18d66b2ae89851ce8906299e9d2a871e0/crypto/rsa/rsa_sp800_56b_gen.c) and [rsa_sp800_56b_check.c:62](https://github.com/openssl/openssl/blob/79c44b4e3044aee9dc9618850d4f1ce067757b4b/crypto/rsa/rsa_sp800_56b_check.c)) / RSA reference material (see [PKCS#1 spec:page 56](https://tools.ietf.org/html/rfc8017), [reference 1](https://www.di-mgt.com.au/crt_rsa.html), [reference 2](https://en.wikipedia.org/wiki/RSA_(cryptosystem)#Using_the_Chinese_remainder_algorithm)) calculate the Chinese Remainder Theorem (CRT) coefficient, represented as the variable `u` in pycryptodome, as `q^-1 mod p` or `q.inverse(p)`, but pycryptodome calculates it as `p^-1 mod q` or `p.inverse(q)` (see [RSA.py:467](https://github.com/Legrandin/pycryptodome/blob/cc46c9f516ac6e7e5a629d60ed282917025926f1/lib/Crypto/PublicKey/RSA.py)).

It was my understanding that p and q are effectively interchangeable in any calculation you use them; however, `p^-1 mod q` clearly yields a different result than `q^-1 mod p`.  I did fork the repo and implement this change, but given that it should be logically identical to the original implementation, I cannot think up a new test that would fail on older versions. Additionally, I do not know if this change would for whatever reason break backwards compatibility.

Should this change be breaking? Backwards compatible?

**Comment by Legrandin** [comment]
Can you please provide more details into your original problem "_convert a non-standard RSA key storage implementation to standard PKCS / PEM_"?

I assume you wanted to use [RSA.construct()](https://www.pycryptodome.org/en/latest/src/public_key/rsa.html#Crypto.PublicKey.RSA.construct) but you only had `q^-1 mod p` and not `p^-1 mod q` as sixth parameter?

If so, you'd better off simply not including the sixth parameter, since PyCryptodome will just regenerated it for you.

Changing the definition of the `u` member is a breaking change to the API, and it is not acceptable. Of course, it would be different if the current math was wrong but it doesn't appear to be case...

**Comment by acabey** [comment]
The problem case is effectively as you described -- I provided the `u` parameter from the stored key, but this causes the `construct` call to fail, given that it calculate `u` differently than other algorithms. The resolution here is not that the way PyCryptodome calculates `u` is wrong (either way is mathematically correct), but that it is a quirk that makes its API behave differently compared to similar projects. The documentation is all correct, so I agree that the solution to this is that I will just program to the provided API and extend the module where needed on my end to provide an alternative interface.
