### ISSUE TITLE
encrypt file using opeenssl/gpg/something that pycryptodome can decrypt

### ISSUE THREAD

**Issue by jpmorris** [Legrandin/pycryptodome#422]
I am decrypting files via:
```
def decrypt(file_name):
    password = bytes(os.getenv('KEY'), 'ascii')
    file_in = open(file_name, "rb")
    iv = file_in.read(16)
    chipered_data = file_in.read()
    file_in.close()
    cipher = AES.new(password, AES.MODE_CFB, iv=iv)
    data = cipher.decrypt(ciphered_data)
    return data
```
Because of workflow requirements, I would like to find a way to encrypt/decrypt (mostly encrypt) via the command line using standard tools that pycroptodome can decrypt.  I am trying to use CFB for it's strength (vs CBC), it's lack of padding requirements, and it's possible comparability with openssl. I would be happy to switch if I knew there was a compatibility.  Is there a way to encrypt a file with openssl/gpg/something else that pycrptodome can read?

**Comment by texadactyl** [comment]
This is neither a bug report nor an enhancement request.  So, it really is not an issue.  You seem to need some guidance.

Let me try to guess what you want to do.  You have an existing workflow that you want to enhance with data protection so that sensitive information is not stored on disk in clear text.
* Password based encryption
* The password will be entered once and housed in a shell environment variable during the workflow execution.
* At the end of the workflow, you are going to use a Python program (re-think your example, by the way) to fetch the protected data and do something with it.

How did I do guessing your intent?

Google "openssl encrypt file python decrypt".  That turned up a lot of help including this one: https://stackoverflow.com/questions/16761458/how-to-decrypt-openssl-aes-encrypted-files-in-python
The example is CBC but the author did the hard work of discovering the salt and iv generated by OpenSSL.

Note that OpenSSL supports CFB even though ```man enc``` doesn't show it.  Google.

Please close this issue.

Good luck!

**Comment by jpmorris** [comment]
thanks for you help.  I was able to get it working with one of the bottom answers in that link.

For others (sorry cant post code right now):
`openssl aes-256-cfb -e -a -salt -pbkdf2 -iter 10000 -in <infile> -out <outfile`

`openssl aes-256-cfb -d -a -pdkdf2 -in <infile> -out <outfile>`

A key for cfb is to make sure that the setment_size=128 to match openssl. 
Also haslib.pbkdf2_hmac() as shown on the SO answer is yoru friend to get back the derivedkey to derive the key and iv from a password (openssl method).
