### ISSUE TITLE
pycryptodomex 3.10.4 on py27 win32 requires VC++14 runtime

### ISSUE THREAD

**Issue by TonyBeswick** [Legrandin/pycryptodome#550]
Python code to reproduce the error:
`from Cryptodome import Cipher`

error produced:
`OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'`

I'm seeing this error on Python 2.7 win32 environments with pycryptodomex version 3.10.4, where vcruntime140.dll is not installed.

The problem goes away if pycryptodomex version 3.10.1 is installed.

pycryptodomex is being installed from wheel: **pycryptodomex-3.10.4-cp27-cp27m-win32.whl**

Found that the `.pyd` files in the Cryptodome\Cipher directory differ between version 3.10.1 and 3.10.4.

Inspection shows that the 3.10.4 .pyd files now depend on `vcruntime140.dll`, whereas as the 3.10.1 files did not.

Installing the (x86) [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=52685) resolves the problem.

I don't see mention of this new dependency in the docs.  **Is this change intentional?**

**Comment by Legrandin** [comment]
Yes, that should have been explained better with 3.10.4.

Microsoft retired support for VS 2008 in April 2021: they can't be found on any official MS site anymore.

VS2008 allowed to compile extensions with the same 9.0 compiler used for the Python 2.7 distribution.

In order to keep the build reasonably simple, PyCryptodome have switched to VS2015 (14.0 compiler). As a consequence, the runtime for 14.0 need to be present.

**Comment by TonyBeswick** [comment]
OK, thanks @Legrandin for confirming.
