### ISSUE TITLE
n

### ISSUE THREAD

**Issue by nothingsec** [Legrandin/pycryptodome#677]

**Comment by nothingsec** [comment]
Python 3.7.3
pycryptodome-3.15.0
macos 10.15.6 
```python
pubobj = Cipher_pkcs1_v1_5.new(RSA.importKey(rsa_privacy_key))
    if length < default_length:
        return pubobj.decrypt(data, None)
    offset = 0
    res = []
    while length - offset > 0:
        # print(length - offset)
        if length - offset > default_length:
            # print(len(data[offset:offset + default_length]))
            res.append(pubobj.decrypt(data[offset:offset + default_length], None))
```

A total of 51 cycles, the first 50 times are normal, the 51st time the value of n changes

<img width="1744" alt="image" src="https://user-images.githubusercontent.com/20467753/198002053-2294f1b4-cb23-49ec-ad79-3035cada2d57.png">

**Comment by Akuli** [comment]
If you want help, please create a **self-contained** example that other people can run without having access to the rest of your project. The code you have posted so far contains lots of undefined variables, and doesn't contain the prints that produced the output you showed.

See also: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by nothingsec** [comment]
@Akuli thanks for your reminder
i create a sample project for test : https://github.com/nothingsec/ransomware-sample
please run command : `python3 main.py de ./priv.key`

**Comment by Varbin** [comment]
@nothingsec I doubt many will help you writing ransomware, even if you claim to have good intentions. Also certainly no one will execute a script from such a project :imp:

While I generally do not help you on this issue because of the aforementioned ethical issues, I will give you a general hint of : Describe what you want to achieve, what you already tried (and what you expected your code should do) and give a *minimal*, *self-contained* and *reproducible* example of your work. Regarding on how such minimal reproducible example should look like, please see the page @Akuli [already mentioned](https://stackoverflow.com/help/minimal-reproducible-example). 
Also _please_ fill the title / description fields with meaningful content ("n" is not a good title for any issue).

**Comment by nothingsec** [comment]
@Varbin  I'm not developing ransomware, I have a file that was encrypted by ransomware, I encountered this problem during the decryption process, and the value of n changed in the middle of calling the module.

**Comment by Legrandin** [comment]
This is normal behavior. The value that gets decrypted at iteration 51 is simply not valid, because it is larger than the RSA modulus (https://www.rfc-editor.org/rfc/rfc8017#section-5.1.2).
