### ISSUE TITLE
No `public_decrypt` functionality.

### ISSUE THREAD

**Issue by Shatnerz** [Legrandin/pycryptodome#715]
Sorry for this low quality issue. I noticed that there is nothing resembling openssl's `public_decrypt` method.

- [similar implementation in Node](https://nodejs.org/api/crypto.html#cryptopublicdecryptkey-buffer)
- [similar implementation in PHP](https://www.php.net/manual/en/function.openssl-public-decrypt.php)

Is this an intentional omission? I know there is some contention around the purposes of `public_decrypt` vs `verify`.

Am I simply missing something obvious here or is this not currently supported?

**Comment by Varbin** [comment]
I guess this is intentional. 

While the mathematical operation of *textbook* RSA signing is equivalent to encryption with a private key and verifying is equivalent to decryption  with a public key, the padding for _secure_ signatures are different to the ones required for encryption.
Both, signing and encryption, are implemented (see https://www.pycryptodome.org/src/signature/signature for signatures and https://www.pycryptodome.org/src/cipher/oaep for encryption) by Pycryptodome, but are correctly named and required the correct padding type.

**Comment by Shatnerz** [comment]
Thanks for the context
